//  布局结构图片映射
export const layoutImgMap = {
    logicalStructure: require('../assets/img/logicalStructure.jpg'),
    mindMap: require('../assets/img/mindMap.jpg'),
    organizationStructure: require('../assets/img/organizationStructure.jpg'),
    catalogOrganization: require('../assets/img/catalogOrganization.jpg'),
    timeline: require('../assets/img/timeline.jpg'),
    timeline2: require('../assets/img/timeline2.jpg'),
    fishbone: require('../assets/img/fishbone.jpg'),
}

//  主题图片映射
export const themeMap = {
    default: require('../assets/img/default.jpg'),
    classic: require('../assets/img/classic.jpg'),
    minions: require('../assets/img/minions.jpg'),
    pinkGrape: require('../assets/img/pinkGrape.jpg'),
    mint: require('../assets/img/mint.jpg'),
    gold: require('../assets/img/gold.jpg'),
    vitalityOrange: require('../assets/img/vitalityOrange.jpg'),
    greenLeaf: require('../assets/img/greenLeaf.jpg'),
    dark2: require('../assets/img/dark2.jpg'),
    skyGreen: require('../assets/img/skyGreen.jpg'),
    classic2: require('../assets/img/classic2.jpg'),
    classic3: require('../assets/img/classic3.jpg'),
    classic4: require('../assets/img/classic4.jpg'),
    classicGreen: require('../assets/img/classicGreen.jpg'),
    classicBlue: require('../assets/img/classicBlue.jpg'),
    blueSky: require('../assets/img/blueSky.jpg'),
    brainImpairedPink: require('../assets/img/brainImpairedPink.jpg'),
    dark: require('../assets/img/dark.jpg'),
    earthYellow: require('../assets/img/earthYellow.jpg'),
    freshGreen: require('../assets/img/freshGreen.jpg'),
    freshRed: require('../assets/img/freshRed.jpg'),
    romanticPurple: require('../assets/img/romanticPurple.jpg'),
    simpleBlack: require('../assets/img/simpleBlack.jpg'),
    courseGreen: require('../assets/img/courseGreen.jpg'),
    coffee: require('../assets/img/coffee.jpg'),
    redSpirit: require('../assets/img/redSpirit.jpg'),
    blackHumour: require('../assets/img/blackHumour.jpg'),
    lateNightOffice: require('../assets/img/lateNightOffice.jpg'),
    blackGold: require('../assets/img/blackGold.jpg'),
    autumn: require('../assets/img/autumn.jpg'),
    avocado: require('../assets/img/avocado.jpg'),
    orangeJuice: require('../assets/img/orangeJuice.jpg'),
}
  