// 深色主题
export default {
  paddingX: 15,
  paddingY: 5,
  imgMaxWidth: 200,
  imgMaxHeight: 100,
  iconSize: 20,
  lineWidth: 1,
  lineColor: '#6366f1',
  lineDasharray: 'none',
  lineFlow: false,
  lineFlowDuration: 1,
  lineFlowForward: true,
  lineStyle: 'straight',
  rootLineKeepSameInCurve: true,
  rootLineStartPositionKeepSameInCurve: false,
  lineRadius: 5,
  showLineMarker: false,
  generalizationLineWidth: 1,
  generalizationLineColor: '#6366f1',
  generalizationLineMargin: 0,
  generalizationNodeMargin: 20,
  associativeLineWidth: 2,
  associativeLineColor: '#a5b4fc',
  associativeLineActiveWidth: 8,
  associativeLineActiveColor: 'rgba(99, 102, 241, 1)',
  associativeLineDasharray: '6,4',
  associativeLineTextColor: '#a5b4fc',
  associativeLineTextFontSize: 14,
  associativeLineTextLineHeight: 1.2,
  associativeLineTextFontFamily: 'Segoe UI, sans-serif',
  backgroundColor: '#1e1e2e',
  backgroundImage: 'none',
  backgroundRepeat: 'no-repeat',
  backgroundPosition: 'center center',
  backgroundSize: 'cover',
  nodeUseLineStyle: false,
  root: {
    shape: 'rectangle',
    fillColor: '#313244',
    fontFamily: 'Segoe UI, sans-serif',
    color: '#cdd6f4',
    fontSize: 18,
    fontWeight: 'bold',
    fontStyle: 'normal',
    borderColor: '#6366f1',
    borderWidth: 2,
    borderDasharray: 'none',
    borderRadius: 8,
    textDecoration: 'none',
    gradientStyle: true,
    startColor: '#313244',
    endColor: '#45475a',
    startDir: [0, 0],
    endDir: [1, 0],
    lineMarkerDir: 'end',
    hoverRectColor: '#6366f1',
    hoverRectRadius: 5,
    textAlign: 'left',
    imgPlacement: 'top',
    tagPlacement: 'right'
  },
  second: {
    shape: 'rectangle',
    marginX: 100,
    marginY: 40,
    fillColor: '#45475a',
    fontFamily: 'Segoe UI, sans-serif',
    color: '#bac2de',
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    borderColor: '#89b4fa',
    borderWidth: 1,
    borderDasharray: 'none',
    borderRadius: 6,
    textDecoration: 'none',
    gradientStyle: false,
    startColor: '#45475a',
    endColor: '#585b70',
    startDir: [0, 0],
    endDir: [1, 0],
    lineMarkerDir: 'end',
    hoverRectColor: '#89b4fa',
    hoverRectRadius: 5,
    textAlign: 'left',
    imgPlacement: 'top',
    tagPlacement: 'right'
  },
  node: {
    shape: 'rectangle',
    marginX: 50,
    marginY: 0,
    fillColor: '#585b70',
    fontFamily: 'Segoe UI, sans-serif',
    color: '#a6adc8',
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    borderColor: '#b4befe',
    borderWidth: 0,
    borderRadius: 4,
    borderDasharray: 'none',
    textDecoration: 'none',
    gradientStyle: false,
    startColor: '#585b70',
    endColor: '#6c7086',
    startDir: [0, 0],
    endDir: [1, 0],
    lineMarkerDir: 'end',
    hoverRectColor: '#b4befe',
    hoverRectRadius: 5,
    textAlign: 'left',
    imgPlacement: 'top',
    tagPlacement: 'right'
  },
  generalization: {
    shape: 'rectangle',
    marginX: 100,
    marginY: 40,
    fillColor: '#45475a',
    fontFamily: 'Segoe UI, sans-serif',
    color: '#bac2de',
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    borderColor: '#89b4fa',
    borderWidth: 1,
    borderDasharray: 'none',
    borderRadius: 6,
    textDecoration: 'none',
    gradientStyle: false,
    startColor: '#45475a',
    endColor: '#585b70',
    startDir: [0, 0],
    endDir: [1, 0],
    hoverRectColor: '#89b4fa',
    hoverRectRadius: 5,
    textAlign: 'left',
    imgPlacement: 'top',
    tagPlacement: 'right'
  }
}
