// 手绘风主题
export default {
  paddingX: 20,
  paddingY: 10,
  imgMaxWidth: 200,
  imgMaxHeight: 100,
  iconSize: 20,
  lineWidth: 3,
  lineColor: '#8B4513',
  lineDasharray: '8,3',
  lineFlow: false,
  lineFlowDuration: 1,
  lineFlowForward: true,
  lineStyle: 'curve',
  rootLineKeepSameInCurve: true,
  rootLineStartPositionKeepSameInCurve: false,
  lineRadius: 10,
  showLineMarker: false,
  generalizationLineWidth: 3,
  generalizationLineColor: '#8B4513',
  generalizationLineMargin: 0,
  generalizationNodeMargin: 20,
  associativeLineWidth: 2,
  associativeLineColor: '#A0522D',
  associativeLineActiveWidth: 8,
  associativeLineActiveColor: 'rgba(160, 82, 45, 1)',
  associativeLineDasharray: '6,4',
  associativeLineTextColor: '#8B4513',
  associativeLineTextFontSize: 14,
  associativeLineTextLineHeight: 1.2,
  associativeLineTextFontFamily: 'Comic Sans MS, cursive',
  backgroundColor: '#FFF8DC',
  backgroundImage: 'none',
  backgroundRepeat: 'no-repeat',
  backgroundPosition: 'center center',
  backgroundSize: 'cover',
  nodeUseLineStyle: false,
  root: {
    shape: 'rectangle',
    fillColor: '#FFE4C4',
    fontFamily: 'Comic Sans MS, cursive',
    color: '#8B4513',
    fontSize: 20,
    fontWeight: 'bold',
    fontStyle: 'normal',
    borderColor: '#DEB887',
    borderWidth: 3,
    borderDasharray: 'none',
    borderRadius: 15,
    textDecoration: 'none',
    gradientStyle: false,
    startColor: '#FFE4C4',
    endColor: '#FFDAB9',
    startDir: [0, 0],
    endDir: [1, 0],
    lineMarkerDir: 'end',
    hoverRectColor: '#DEB887',
    hoverRectRadius: 10,
    textAlign: 'left',
    imgPlacement: 'top',
    tagPlacement: 'right'
  },
  second: {
    shape: 'rectangle',
    marginX: 100,
    marginY: 50,
    fillColor: '#FFFACD',
    fontFamily: 'Comic Sans MS, cursive',
    color: '#A0522D',
    fontSize: 18,
    fontWeight: 'normal',
    fontStyle: 'normal',
    borderColor: '#DEB887',
    borderWidth: 2,
    borderDasharray: 'none',
    borderRadius: 12,
    textDecoration: 'none',
    gradientStyle: false,
    startColor: '#FFFACD',
    endColor: '#FFE4B5',
    startDir: [0, 0],
    endDir: [1, 0],
    lineMarkerDir: 'end',
    hoverRectColor: '#DEB887',
    hoverRectRadius: 10,
    textAlign: 'left',
    imgPlacement: 'top',
    tagPlacement: 'right'
  },
  node: {
    shape: 'rectangle',
    marginX: 50,
    marginY: 0,
    fillColor: '#FFFAF0',
    fontFamily: 'Comic Sans MS, cursive',
    color: '#CD853F',
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    borderColor: '#DEB887',
    borderWidth: 2,
    borderRadius: 10,
    borderDasharray: 'none',
    textDecoration: 'none',
    gradientStyle: false,
    startColor: '#FFFAF0',
    endColor: '#FFF5EE',
    startDir: [0, 0],
    endDir: [1, 0],
    lineMarkerDir: 'end',
    hoverRectColor: '#DEB887',
    hoverRectRadius: 10,
    textAlign: 'left',
    imgPlacement: 'top',
    tagPlacement: 'right'
  },
  generalization: {
    shape: 'rectangle',
    marginX: 100,
    marginY: 50,
    fillColor: '#FFE4C4',
    fontFamily: 'Comic Sans MS, cursive',
    color: '#A0522D',
    fontSize: 18,
    fontWeight: 'normal',
    fontStyle: 'normal',
    borderColor: '#DEB887',
    borderWidth: 2,
    borderDasharray: 'none',
    borderRadius: 12,
    textDecoration: 'none',
    gradientStyle: false,
    startColor: '#FFE4C4',
    endColor: '#FFDAB9',
    startDir: [0, 0],
    endDir: [1, 0],
    hoverRectColor: '#DEB887',
    hoverRectRadius: 10,
    textAlign: 'left',
    imgPlacement: 'top',
    tagPlacement: 'right'
  }
}
