// 简约风主题
export default {
  paddingX: 15,
  paddingY: 5,
  imgMaxWidth: 200,
  imgMaxHeight: 100,
  iconSize: 20,
  lineWidth: 1,
  lineColor: '#9ca3af',
  lineDasharray: 'none',
  lineFlow: false,
  lineFlowDuration: 1,
  lineFlowForward: true,
  lineStyle: 'straight',
  rootLineKeepSameInCurve: true,
  rootLineStartPositionKeepSameInCurve: false,
  lineRadius: 5,
  showLineMarker: false,
  generalizationLineWidth: 1,
  generalizationLineColor: '#9ca3af',
  generalizationLineMargin: 0,
  generalizationNodeMargin: 20,
  associativeLineWidth: 2,
  associativeLineColor: '#6b7280',
  associativeLineActiveWidth: 8,
  associativeLineActiveColor: 'rgba(107, 114, 128, 1)',
  associativeLineDasharray: '6,4',
  associativeLineTextColor: '#6b7280',
  associativeLineTextFontSize: 14,
  associativeLineTextLineHeight: 1.2,
  associativeLineTextFontFamily: 'Arial, sans-serif',
  backgroundColor: '#ffffff',
  backgroundImage: 'none',
  backgroundRepeat: 'no-repeat',
  backgroundPosition: 'center center',
  backgroundSize: 'cover',
  nodeUseLineStyle: true,
  root: {
    shape: 'rectangle',
    fillColor: '#f3f4f6',
    fontFamily: 'Arial, sans-serif',
    color: '#1f2937',
    fontSize: 18,
    fontWeight: 'normal',
    fontStyle: 'normal',
    borderColor: '#d1d5db',
    borderWidth: 1,
    borderDasharray: 'none',
    borderRadius: 4,
    textDecoration: 'none',
    gradientStyle: false,
    startColor: '#f3f4f6',
    endColor: '#e5e7eb',
    startDir: [0, 0],
    endDir: [1, 0],
    lineMarkerDir: 'end',
    hoverRectColor: '',
    hoverRectRadius: 5,
    textAlign: 'left',
    imgPlacement: 'top',
    tagPlacement: 'right'
  },
  second: {
    shape: 'rectangle',
    marginX: 100,
    marginY: 40,
    fillColor: 'transparent',
    fontFamily: 'Arial, sans-serif',
    color: '#374151',
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    borderColor: 'transparent',
    borderWidth: 0,
    borderDasharray: 'none',
    borderRadius: 4,
    textDecoration: 'none',
    gradientStyle: false,
    startColor: '#f3f4f6',
    endColor: '#e5e7eb',
    startDir: [0, 0],
    endDir: [1, 0],
    lineMarkerDir: 'end',
    hoverRectColor: '',
    hoverRectRadius: 5,
    textAlign: 'left',
    imgPlacement: 'top',
    tagPlacement: 'right'
  },
  node: {
    shape: 'rectangle',
    marginX: 50,
    marginY: 0,
    fillColor: 'transparent',
    fontFamily: 'Arial, sans-serif',
    color: '#6b7280',
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    borderColor: 'transparent',
    borderWidth: 0,
    borderRadius: 4,
    borderDasharray: 'none',
    textDecoration: 'none',
    gradientStyle: false,
    startColor: '#f3f4f6',
    endColor: '#e5e7eb',
    startDir: [0, 0],
    endDir: [1, 0],
    lineMarkerDir: 'end',
    hoverRectColor: '',
    hoverRectRadius: 5,
    textAlign: 'left',
    imgPlacement: 'top',
    tagPlacement: 'right'
  },
  generalization: {
    shape: 'rectangle',
    marginX: 100,
    marginY: 40,
    fillColor: '#f9fafb',
    fontFamily: 'Arial, sans-serif',
    color: '#4b5563',
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    borderColor: '#e5e7eb',
    borderWidth: 1,
    borderDasharray: 'none',
    borderRadius: 4,
    textDecoration: 'none',
    gradientStyle: false,
    startColor: '#f3f4f6',
    endColor: '#e5e7eb',
    startDir: [0, 0],
    endDir: [1, 0],
    hoverRectColor: '',
    hoverRectRadius: 5,
    textAlign: 'left',
    imgPlacement: 'top',
    tagPlacement: 'right'
  }
}
