// 彩虹主题
export default {
  paddingX: 15,
  paddingY: 5,
  imgMaxWidth: 200,
  imgMaxHeight: 100,
  iconSize: 20,
  lineWidth: 2,
  lineColor: '#ec4899',
  lineDasharray: 'none',
  lineFlow: false,
  lineFlowDuration: 1,
  lineFlowForward: true,
  lineStyle: 'curve',
  rootLineKeepSameInCurve: true,
  rootLineStartPositionKeepSameInCurve: false,
  lineRadius: 10,
  showLineMarker: false,
  generalizationLineWidth: 2,
  generalizationLineColor: '#f472b6',
  generalizationLineMargin: 0,
  generalizationNodeMargin: 20,
  associativeLineWidth: 2,
  associativeLineColor: '#a855f7',
  associativeLineActiveWidth: 8,
  associativeLineActiveColor: 'rgba(168, 85, 247, 1)',
  associativeLineDasharray: '8,4',
  associativeLineTextColor: '#7c3aed',
  associativeLineTextFontSize: 14,
  associativeLineTextLineHeight: 1.2,
  associativeLineTextFontFamily: 'Arial, sans-serif',
  backgroundColor: '#fdf4ff',
  backgroundImage: 'none',
  backgroundRepeat: 'no-repeat',
  backgroundPosition: 'center center',
  backgroundSize: 'cover',
  nodeUseLineStyle: false,
  root: {
    shape: 'rectangle',
    fillColor: '#ef4444',
    fontFamily: 'Arial, sans-serif',
    color: '#ffffff',
    fontSize: 20,
    fontWeight: 'bold',
    fontStyle: 'normal',
    borderColor: '#dc2626',
    borderWidth: 0,
    borderDasharray: 'none',
    borderRadius: 12,
    textDecoration: 'none',
    gradientStyle: false,
    startColor: '#ef4444',
    endColor: '#dc2626',
    startDir: [0, 0],
    endDir: [1, 0],
    lineMarkerDir: 'end',
    hoverRectColor: '#fca5a5',
    hoverRectRadius: 10,
    textAlign: 'left',
    imgPlacement: 'top',
    tagPlacement: 'right'
  },
  second: {
    shape: 'rectangle',
    marginX: 100,
    marginY: 50,
    fillColor: '#f97316',
    fontFamily: 'Arial, sans-serif',
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
    fontStyle: 'normal',
    borderColor: '#ea580c',
    borderWidth: 0,
    borderDasharray: 'none',
    borderRadius: 10,
    textDecoration: 'none',
    gradientStyle: false,
    startColor: '#f97316',
    endColor: '#ea580c',
    startDir: [0, 0],
    endDir: [1, 0],
    lineMarkerDir: 'end',
    hoverRectColor: '#fdba74',
    hoverRectRadius: 10,
    textAlign: 'left',
    imgPlacement: 'top',
    tagPlacement: 'right'
  },
  node: {
    shape: 'rectangle',
    marginX: 50,
    marginY: 0,
    fillColor: '#22c55e',
    fontFamily: 'Arial, sans-serif',
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
    fontStyle: 'normal',
    borderColor: '#16a34a',
    borderWidth: 0,
    borderRadius: 8,
    borderDasharray: 'none',
    textDecoration: 'none',
    gradientStyle: false,
    startColor: '#22c55e',
    endColor: '#16a34a',
    startDir: [0, 0],
    endDir: [1, 0],
    lineMarkerDir: 'end',
    hoverRectColor: '#86efac',
    hoverRectRadius: 10,
    textAlign: 'left',
    imgPlacement: 'top',
    tagPlacement: 'right'
  },
  generalization: {
    shape: 'rectangle',
    marginX: 100,
    marginY: 50,
    fillColor: '#8b5cf6',
    fontFamily: 'Arial, sans-serif',
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
    fontStyle: 'normal',
    borderColor: '#7c3aed',
    borderWidth: 0,
    borderDasharray: 'none',
    borderRadius: 10,
    textDecoration: 'none',
    gradientStyle: false,
    startColor: '#8b5cf6',
    endColor: '#7c3aed',
    startDir: [0, 0],
    endDir: [1, 0],
    hoverRectColor: '#c4b5fd',
    hoverRectRadius: 10,
    textAlign: 'left',
    imgPlacement: 'top',
    tagPlacement: 'right'
  }
}
