// 科技风主题
export default {
  paddingX: 20,
  paddingY: 8,
  imgMaxWidth: 200,
  imgMaxHeight: 100,
  iconSize: 20,
  lineWidth: 2,
  lineColor: '#00ffff',
  lineDasharray: 'none',
  lineFlow: false,
  lineFlowDuration: 1,
  lineFlowForward: true,
  lineStyle: 'curve',
  rootLineKeepSameInCurve: true,
  rootLineStartPositionKeepSameInCurve: false,
  lineRadius: 5,
  showLineMarker: false,
  generalizationLineWidth: 2,
  generalizationLineColor: '#00ffff',
  generalizationLineMargin: 0,
  generalizationNodeMargin: 20,
  associativeLineWidth: 2,
  associativeLineColor: '#00d4ff',
  associativeLineActiveWidth: 8,
  associativeLineActiveColor: 'rgba(0, 212, 255, 1)',
  associativeLineDasharray: '10,5',
  associativeLineTextColor: '#00ffff',
  associativeLineTextFontSize: 14,
  associativeLineTextLineHeight: 1.2,
  associativeLineTextFontFamily: 'Consolas, monospace',
  backgroundColor: '#0a0a1a',
  backgroundImage: 'none',
  backgroundRepeat: 'no-repeat',
  backgroundPosition: 'center center',
  backgroundSize: 'cover',
  nodeUseLineStyle: false,
  root: {
    shape: 'rectangle',
    fillColor: '#1a1a2e',
    fontFamily: 'Consolas, monospace',
    color: '#00ffff',
    fontSize: 18,
    fontWeight: 'bold',
    fontStyle: 'normal',
    borderColor: '#00ffff',
    borderWidth: 2,
    borderDasharray: 'none',
    borderRadius: 8,
    textDecoration: 'none',
    gradientStyle: true,
    startColor: '#1a1a2e',
    endColor: '#16213e',
    startDir: [0, 0],
    endDir: [1, 0],
    lineMarkerDir: 'end',
    hoverRectColor: '#00ffff',
    hoverRectRadius: 5,
    textAlign: 'left',
    imgPlacement: 'top',
    tagPlacement: 'right'
  },
  second: {
    shape: 'rectangle',
    marginX: 100,
    marginY: 40,
    fillColor: '#0f0f1e',
    fontFamily: 'Consolas, monospace',
    color: '#00d4ff',
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    borderColor: '#00d4ff',
    borderWidth: 1,
    borderDasharray: 'none',
    borderRadius: 6,
    textDecoration: 'none',
    gradientStyle: true,
    startColor: '#0f0f1e',
    endColor: '#1a1a2e',
    startDir: [0, 0],
    endDir: [1, 0],
    lineMarkerDir: 'end',
    hoverRectColor: '#00d4ff',
    hoverRectRadius: 5,
    textAlign: 'left',
    imgPlacement: 'top',
    tagPlacement: 'right'
  },
  node: {
    shape: 'rectangle',
    marginX: 50,
    marginY: 0,
    fillColor: '#0a0a1a',
    fontFamily: 'Consolas, monospace',
    color: '#88ffff',
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    borderColor: '#00ffff',
    borderWidth: 1,
    borderRadius: 4,
    borderDasharray: 'none',
    textDecoration: 'none',
    gradientStyle: false,
    startColor: '#0a0a1a',
    endColor: '#0f0f1e',
    startDir: [0, 0],
    endDir: [1, 0],
    lineMarkerDir: 'end',
    hoverRectColor: '#00ffff',
    hoverRectRadius: 5,
    textAlign: 'left',
    imgPlacement: 'top',
    tagPlacement: 'right'
  },
  generalization: {
    shape: 'rectangle',
    marginX: 100,
    marginY: 40,
    fillColor: '#1a1a2e',
    fontFamily: 'Consolas, monospace',
    color: '#00d4ff',
    fontSize: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    borderColor: '#00ffff',
    borderWidth: 1,
    borderDasharray: 'none',
    borderRadius: 6,
    textDecoration: 'none',
    gradientStyle: true,
    startColor: '#1a1a2e',
    endColor: '#16213e',
    startDir: [0, 0],
    endDir: [1, 0],
    hoverRectColor: '#00ffff',
    hoverRectRadius: 5,
    textAlign: 'left',
    imgPlacement: 'top',
    tagPlacement: 'right'
  }
}
