declare namespace _default {
    const paddingX: number;
    const paddingY: number;
    const imgMaxWidth: number;
    const imgMaxHeight: number;
    const iconSize: number;
    const lineWidth: number;
    const lineColor: string;
    const lineDasharray: string;
    const lineStyle: string;
    const rootLineKeepSameInCurve: boolean;
    const generalizationLineWidth: number;
    const generalizationLineColor: string;
    const generalizationLineMargin: number;
    const generalizationNodeMargin: number;
    const associativeLineWidth: number;
    const associativeLineColor: string;
    const associativeLineActiveWidth: number;
    const associativeLineActiveColor: string;
    const associativeLineTextColor: string;
    const associativeLineTextFontSize: number;
    const associativeLineTextLineHeight: number;
    const associativeLineTextFontFamily: string;
    const backgroundColor: string;
    const backgroundImage: string;
    const backgroundRepeat: string;
    const backgroundPosition: string;
    const backgroundSize: string;
    const nodeUseLineStyle: boolean;
    namespace root {
        const shape: string;
        const fillColor: string;
        const fontFamily: string;
        const color: string;
        const fontSize: number;
        const fontWeight: string;
        const fontStyle: string;
        const lineHeight: number;
        const borderColor: string;
        const borderWidth: number;
        const borderDasharray: string;
        const borderRadius: number;
        const textDecoration: string;
    }
    namespace second {
        const shape_1: string;
        export { shape_1 as shape };
        export const marginX: number;
        export const marginY: number;
        const fillColor_1: string;
        export { fillColor_1 as fillColor };
        const fontFamily_1: string;
        export { fontFamily_1 as fontFamily };
        const color_1: string;
        export { color_1 as color };
        const fontSize_1: number;
        export { fontSize_1 as fontSize };
        const fontWeight_1: string;
        export { fontWeight_1 as fontWeight };
        const fontStyle_1: string;
        export { fontStyle_1 as fontStyle };
        const lineHeight_1: number;
        export { lineHeight_1 as lineHeight };
        const borderColor_1: string;
        export { borderColor_1 as borderColor };
        const borderWidth_1: number;
        export { borderWidth_1 as borderWidth };
        const borderDasharray_1: string;
        export { borderDasharray_1 as borderDasharray };
        const borderRadius_1: number;
        export { borderRadius_1 as borderRadius };
        const textDecoration_1: string;
        export { textDecoration_1 as textDecoration };
    }
    namespace node {
        const shape_2: string;
        export { shape_2 as shape };
        const marginX_1: number;
        export { marginX_1 as marginX };
        const marginY_1: number;
        export { marginY_1 as marginY };
        const fillColor_2: string;
        export { fillColor_2 as fillColor };
        const fontFamily_2: string;
        export { fontFamily_2 as fontFamily };
        const color_2: string;
        export { color_2 as color };
        const fontSize_2: number;
        export { fontSize_2 as fontSize };
        const fontWeight_2: string;
        export { fontWeight_2 as fontWeight };
        const fontStyle_2: string;
        export { fontStyle_2 as fontStyle };
        const lineHeight_2: number;
        export { lineHeight_2 as lineHeight };
        const borderColor_2: string;
        export { borderColor_2 as borderColor };
        const borderWidth_2: number;
        export { borderWidth_2 as borderWidth };
        const borderRadius_2: number;
        export { borderRadius_2 as borderRadius };
        const borderDasharray_2: string;
        export { borderDasharray_2 as borderDasharray };
        const textDecoration_2: string;
        export { textDecoration_2 as textDecoration };
    }
    namespace generalization {
        const shape_3: string;
        export { shape_3 as shape };
        const marginX_2: number;
        export { marginX_2 as marginX };
        const marginY_2: number;
        export { marginY_2 as marginY };
        const fillColor_3: string;
        export { fillColor_3 as fillColor };
        const fontFamily_3: string;
        export { fontFamily_3 as fontFamily };
        const color_3: string;
        export { color_3 as color };
        const fontSize_3: number;
        export { fontSize_3 as fontSize };
        const fontWeight_3: string;
        export { fontWeight_3 as fontWeight };
        const fontStyle_3: string;
        export { fontStyle_3 as fontStyle };
        const lineHeight_3: number;
        export { lineHeight_3 as lineHeight };
        const borderColor_3: string;
        export { borderColor_3 as borderColor };
        const borderWidth_3: number;
        export { borderWidth_3 as borderWidth };
        const borderDasharray_3: string;
        export { borderDasharray_3 as borderDasharray };
        const borderRadius_3: number;
        export { borderRadius_3 as borderRadius };
        const textDecoration_3: string;
        export { textDecoration_3 as textDecoration };
    }
}
export default _default;
export const supportActiveStyle: string[];
export function checkIsNodeSizeIndependenceConfig(config: any): boolean;
export const lineStyleProps: string[];
